version: 0.2
env:
  shell: bash
  parameter-store:
    DB_SECRET_ID: "/${APP_NAME}/pipelines/${PIPELINE_NAME}/${ENVIRONMENT}/db/secret_id"
    PGHOST:  "/${APP_NAME}/pipelines/${PIPELINE_NAME}/${ENVIRONMENT}/db/host"
    PGPORT:  "/${APP_NAME}/pipelines/${PIPELINE_NAME}/${ENVIRONMENT}/db/port"
  secrets-manager:
    PGUSER: "${DB_SECRET_ID}:username"
    PGPASSWORD: "${DB_SECRET_ID}:password"



phases:
  install:
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - source ~/.bashrc
      - nvm install v18.19
      - npm install -G yarn

  build:
    commands:
      # Verify the values of vars passed in via the project
      - echo "${WORKSPACE}"
      - cd ${CODEBUILD_SRC_DIR}/backend/core
      - export DATABASE_URL = "postgresql://${PGUSER}@${PGHOST}:${PGPORT}/${PGDATABASE}"
      - yarn install
      - yarn db:migration:run