version: 0.2
env:
  shell: bash
  variables:
    # This var is used to define which version of terraform to use
    # This can be overridden by passing a TF_VERSION var to the build
    TF_VERSION: "1.7.4"
    # This var tells terraform that we're running in a CI/CD pipeline
    TF_IN_AUTOMATION: "true"
    # This var tells terraform to disable prompts for missing variables
    TF_INPUT: "false"
phases:
  build:
    commands:
      # Verify the values of vars passed in via the project
      - echo "${WORKSPACE}"
      - echo ${STACK_PREFIX}
      - npm install -G yarn
      - cd ${CODEBUILD_SRC_DIR_doorway_source}/backend/core
      # Have to init again to make sure providers are present

      - yarn install
      - yarn build