version: 0.2
env:
  shell: bash
  parameter-store:
    DB_SECRET_ID: "/${APP_NAME}/pipelines/${PIPELINE_NAME}/${ENVIRONMENT}/db/secret_id"
    PGHOST:  "/${APP_NAME}/pipelines/${PIPELINE_NAME}/${ENVIRONMENT}/db/host"
    PGPORT:  "/${APP_NAME}/pipelines/${PIPELINE_NAME}/${ENVIRONMENT}/db/port"



phases:
  install:
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      #- \[ -s "$NVM_DIR/nvm.sh" \]
      - export NVM_DIR="$HOME/.nvm"
      - . "$NVM_DIR/nvm.sh" && nvm install v18.19
      - npm install -G yarn
      - sudo apt install -y  postgresql-client-16

  build:
    commands:
      # Verify the values of vars passed in via the project

      - echo "${WORKSPACE}"
      - cd ${CODEBUILD_SRC_DIR_doorway_source}/backend/core
      - export PGUSER=$(aws secretsmanager get-secret-value --secret-id ${DB_SECRET_ID} --query SecretString|jq -r|jq -r .username)
      - export PGPASSWORD=$(aws secretsmanager get-secret-value --secret-id ${DB_SECRET_ID} --query SecretString|jq -r|jq -r .password)
      - psql -U ${PGUSER} -c "CREATE DATABASE doorway;"
      - echo $PGUSER
      - export DATABASE_URL="postgresql://${PGUSER}@${PGHOST}:${PGPORT}/${PGDATABASE}"
      - yarn install
      - yarn db:migration:run