version: 0.2
env:
  shell: bash
  parameter-store:
    PGDATABASE: "/${STACK_PREFIX}/db/name"
    DATABASE_URL: "/${STACK_PREFIX}/db/url"
    DATABASE_PORT: "/${STACK_PREFIX}/db/port"

  secrets-manager:
    PUSER: "${DB_CREDS_ARN}:username"
    PGPASSWORD: "${DB_CREDS_ARN}:password"

phases:
  build:
    commands:
      # Verify the values of vars passed in via the project
      - echo "${WORKSPACE}"
      - echo ${STACK_PREFIX}
      - npm install -G yarn
      - cd ${CODEBUILD_SRC_DIR_doorway_source}/backend/core
      # Have to init again to make sure providers are present

      - yarn db:migration:run