version: 0.2
env:
  shell: bash
  parameter-store:
    DB_SECRET_ID: "/${APP_NAME}/pipelines/${PIPELINE_NAME}/${ENVIRONMENT}/db/secret_id"
    PGHOST:  "/${APP_NAME}/pipelines/${PIPELINE_NAME}/${ENVIRONMENT}/db/host"
    PGPORT:  "/${APP_NAME}/pipelines/${PIPELINE_NAME}/${ENVIRONMENT}/db/port"
  secrets-manager:
    PGUSER: "${DB_SECRET_ID}:username"
    PGPASSWORD: "${DB_SECRET_ID}:password"



phases:
  build:
    commands:
      # Verify the values of vars passed in via the project
      - echo "${WORKSPACE}"
      - echo ${STACK_PREFIX}
      - npm install -G yarn
      - cd ${CODEBUILD_SRC_DIR_doorway_source}/backend/core
      - export DATABASE_URL = "postgresql://${PGUSER}@${PGHOST}:${PGPORT}/${PGDATABASE}"
      - yarn db:migration:run